/**
 * Chat API SDK
 * The SDK allows you to receive and send messages through your WhatsApp account. [Sign up now](https://app.chat-api.com/)  The Chat API is based on the WhatsApp WEB protocol and excludes the ban both when using libraries from mgp25 and the like. Despite this, your account can be banned by anti-spam system WhatsApp after several clicking the \"block\" button.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sale@chat-api.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class GroupParticipantAction {
    /**
    * Chat ID from the chat list. Examples: 19680561234-1479621234@g.us for the group.
    */
    'groupId': string;
    /**
    * **Required if participantPhone is not set**  Chat ID from the message list. Examples: 17633123456@c.us. Used instead of the participantPhone parameter.
    */
    'participantChatId': string;
    /**
    * **Required if participantChatId is not set**  A phone number starting with the country code. You do not need to add your number.   USA example: 17472822486.
    */
    'participantPhone'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "groupId",
            "baseName": "groupId",
            "type": "string"
        },
        {
            "name": "participantChatId",
            "baseName": "participantChatId",
            "type": "string"
        },
        {
            "name": "participantPhone",
            "baseName": "participantPhone",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return GroupParticipantAction.attributeTypeMap;
    }
}

