/**
 * Chat API SDK
 * The SDK allows you to receive and send messages through your WhatsApp account. [Sign up now](https://app.chat-api.com/)  The Chat API is based on the WhatsApp WEB protocol and excludes the ban both when using libraries from mgp25 and the like. Despite this, your account can be banned by anti-spam system WhatsApp after several clicking the \"block\" button.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sale@chat-api.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { InstanceStatusStatusDataActions } from './instanceStatusStatusDataActions';

/**
* More information about instance status
*/
export class InstanceStatusStatusData {
    /**
    * Instance Substatus
    */
    'substatus'?: InstanceStatusStatusData.SubstatusEnum;
    /**
    * Status title in the language of the instance
    */
    'title'?: string;
    /**
    * Status message in the language of the instance
    */
    'msg'?: string;
    /**
    * Additional status message in the language of the instance
    */
    'submsg'?: string;
    'actions'?: InstanceStatusStatusDataActions;
    /**
    * The reason why the instance is in \"loading\" status
    */
    'reason'?: InstanceStatusStatusData.ReasonEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "substatus",
            "baseName": "substatus",
            "type": "InstanceStatusStatusData.SubstatusEnum"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "msg",
            "baseName": "msg",
            "type": "string"
        },
        {
            "name": "submsg",
            "baseName": "submsg",
            "type": "string"
        },
        {
            "name": "actions",
            "baseName": "actions",
            "type": "InstanceStatusStatusDataActions"
        },
        {
            "name": "reason",
            "baseName": "reason",
            "type": "InstanceStatusStatusData.ReasonEnum"
        }    ];

    static getAttributeTypeMap() {
        return InstanceStatusStatusData.attributeTypeMap;
    }
}

export namespace InstanceStatusStatusData {
    export enum SubstatusEnum {
        Normal = <any> 'normal',
        Loading = <any> 'loading',
        Offline = <any> 'offline',
        Expired = <any> 'expired',
        Opening = <any> 'opening',
        Pairing = <any> 'pairing',
        Timeout = <any> 'timeout',
        Computer = <any> 'computer',
        Phone = <any> 'phone',
        BatteryLow1 = <any> 'battery_low_1',
        BatteryLow2 = <any> 'battery_low_2'
    }
    export enum ReasonEnum {
        Connecting = <any> 'connecting',
        Syncing = <any> 'syncing',
        Offline = <any> 'offline',
        Proxyblock = <any> 'proxyblock',
        Conflict = <any> 'conflict'
    }
}
