/**
 * Chat API SDK
 * The SDK allows you to receive and send messages through your WhatsApp account. [Sign up now](https://app.chat-api.com/)  The Chat API is based on the WhatsApp WEB protocol and excludes the ban both when using libraries from mgp25 and the like. Despite this, your account can be banned by anti-spam system WhatsApp after several clicking the \"block\" button.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sale@chat-api.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class OutboundMessage {
    /**
    * message id in queue
    */
    'id'?: number;
    /**
    * text message in queue
    */
    'body'?: string;
    /**
    * type of the message in queue
    */
    'type'?: OutboundMessage.TypeEnum;
    /**
    * Last try time to send a message
    */
    'lastTry'?: number;
    /**
    * Additional message data
    */
    'metadata'?: object;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "body",
            "baseName": "body",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "OutboundMessage.TypeEnum"
        },
        {
            "name": "lastTry",
            "baseName": "last_try",
            "type": "number"
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "object"
        }    ];

    static getAttributeTypeMap() {
        return OutboundMessage.attributeTypeMap;
    }
}

export namespace OutboundMessage {
    export enum TypeEnum {
        Chat = <any> 'chat',
        Image = <any> 'image',
        Ptt = <any> 'ptt',
        Document = <any> 'document',
        Audio = <any> 'audio',
        Video = <any> 'video',
        Location = <any> 'location',
        CallLog = <any> 'call_log'
    }
}
