/**
 * Chat API SDK
 * The SDK allows you to receive and send messages through your WhatsApp account. [Sign up now](https://app.chat-api.com/)  The Chat API is based on the WhatsApp WEB protocol and excludes the ban both when using libraries from mgp25 and the like. Despite this, your account can be banned by anti-spam system WhatsApp after several clicking the \"block\" button.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sale@chat-api.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class OutboundAction {
    /**
    * action id in queue
    */
    'id'?: number;
    /**
    * type of the action in queue
    */
    'type'?: OutboundAction.TypeEnum;
    /**
    * Last try time to execute a action
    */
    'lastTry'?: number;
    /**
    * Additional action data
    */
    'jsonData'?: object;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "OutboundAction.TypeEnum"
        },
        {
            "name": "lastTry",
            "baseName": "last_try",
            "type": "number"
        },
        {
            "name": "jsonData",
            "baseName": "json_data",
            "type": "object"
        }    ];

    static getAttributeTypeMap() {
        return OutboundAction.attributeTypeMap;
    }
}

export namespace OutboundAction {
    export enum TypeEnum {
        CreateGroup = <any> 'create group',
        AddGroupParticipant = <any> 'add group participant',
        RemoveGroupParticipant = <any> 'remove group participant',
        PromoteGroupParticipant = <any> 'promote group participant',
        DemoteGroupParticipant = <any> 'demote group participant',
        ReadChat = <any> 'read chat'
    }
}
