/**
 * Chat API SDK
 * The SDK allows you to receive and send messages through your WhatsApp account. [Sign up now](https://app.chat-api.com/)  The Chat API is based on the WhatsApp WEB protocol and excludes the ban both when using libraries from mgp25 and the like. Despite this, your account can be banned by anti-spam system WhatsApp after several clicking the \"block\" button.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sale@chat-api.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class CreateGroupAction {
    /**
    * Name of the group being created
    */
    'groupName': string;
    /**
    * **Required if phones is not set**  An array of new participients chatIds. 
    */
    'chatIds'?: Array<string>;
    /**
    * **Required if chatIds is not set**  An array of phones starting with the country code. You do not need to add your number.   USA example: [17472822486\'].
    */
    'phones'?: Array<number>;
    /**
    * The text of the message that will be sent to the group when it is created. If you do not set a parameter, the message will not be sent
    */
    'messageText'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "groupName",
            "baseName": "groupName",
            "type": "string"
        },
        {
            "name": "chatIds",
            "baseName": "chatIds",
            "type": "Array<string>"
        },
        {
            "name": "phones",
            "baseName": "phones",
            "type": "Array<number>"
        },
        {
            "name": "messageText",
            "baseName": "messageText",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CreateGroupAction.attributeTypeMap;
    }
}

