"use strict";
/**
 * Chat API SDK
 * The SDK allows you to receive and send messages through your WhatsApp account. [Sign up now](https://app.chat-api.com/)  The Chat API is based on the WhatsApp WEB protocol and excludes the ban both when using libraries from mgp25 and the like. Despite this, your account can be banned by anti-spam system WhatsApp after several clicking the \"block\" button.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sale@chat-api.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.InlineResponse2001 = void 0;
var InlineResponse2001 = /** @class */ (function () {
    function InlineResponse2001() {
    }
    InlineResponse2001.getAttributeTypeMap = function () {
        return InlineResponse2001.attributeTypeMap;
    };
    InlineResponse2001.discriminator = undefined;
    InlineResponse2001.attributeTypeMap = [
        {
            "name": "accountStatus",
            "baseName": "accountStatus",
            "type": "InlineResponse2001.AccountStatusEnum"
        }
    ];
    return InlineResponse2001;
}());
exports.InlineResponse2001 = InlineResponse2001;
(function (InlineResponse2001) {
    var AccountStatusEnum;
    (function (AccountStatusEnum) {
        AccountStatusEnum[AccountStatusEnum["SentToWhatsApp"] = 'Takeover request sent to WhatsApp'] = "SentToWhatsApp";
        AccountStatusEnum[AccountStatusEnum["NotSentBecauseReasonDontEqualsConflict"] = 'Takeover request not sent because reason don\'t equals \"conflict\"'] = "NotSentBecauseReasonDontEqualsConflict";
    })(AccountStatusEnum = InlineResponse2001.AccountStatusEnum || (InlineResponse2001.AccountStatusEnum = {}));
})(InlineResponse2001 = exports.InlineResponse2001 || (exports.InlineResponse2001 = {}));
exports.InlineResponse2001 = InlineResponse2001;
