"use strict";
/**
 * Chat API SDK
 * The SDK allows you to receive and send messages through your WhatsApp account. [Sign up now](https://app.chat-api.com/)  The Chat API is based on the WhatsApp WEB protocol and excludes the ban both when using libraries from mgp25 and the like. Despite this, your account can be banned by anti-spam system WhatsApp after several clicking the \"block\" button.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sale@chat-api.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.InlineResponse2005Update = void 0;
/**
* An object that lists the fields changed in the request
*/
var InlineResponse2005Update = /** @class */ (function () {
    function InlineResponse2005Update() {
    }
    InlineResponse2005Update.getAttributeTypeMap = function () {
        return InlineResponse2005Update.attributeTypeMap;
    };
    InlineResponse2005Update.discriminator = undefined;
    InlineResponse2005Update.attributeTypeMap = [
        {
            "name": "webhookUrl",
            "baseName": "webhookUrl",
            "type": "string"
        },
        {
            "name": "ackNotificationsOn",
            "baseName": "ackNotificationsOn",
            "type": "boolean"
        },
        {
            "name": "chatUpdateOn",
            "baseName": "chatUpdateOn",
            "type": "boolean"
        },
        {
            "name": "videoUploadOn",
            "baseName": "videoUploadOn",
            "type": "boolean"
        },
        {
            "name": "proxy",
            "baseName": "proxy",
            "type": "string"
        },
        {
            "name": "guaranteedHooks",
            "baseName": "guaranteedHooks",
            "type": "boolean"
        },
        {
            "name": "ignoreOldMessages",
            "baseName": "ignoreOldMessages",
            "type": "boolean"
        },
        {
            "name": "processArchive",
            "baseName": "processArchive",
            "type": "boolean"
        },
        {
            "name": "instanceStatuses",
            "baseName": "instanceStatuses",
            "type": "boolean"
        },
        {
            "name": "webhookStatuses",
            "baseName": "webhookStatuses",
            "type": "boolean"
        },
        {
            "name": "statusNotificationsOn",
            "baseName": "statusNotificationsOn",
            "type": "boolean"
        }
    ];
    return InlineResponse2005Update;
}());
exports.InlineResponse2005Update = InlineResponse2005Update;
