"use strict";
/**
 * Chat API SDK
 * The SDK allows you to receive and send messages through your WhatsApp account. [Sign up now](https://app.chat-api.com/)  The Chat API is based on the WhatsApp WEB protocol and excludes the ban both when using libraries from mgp25 and the like. Despite this, your account can be banned by anti-spam system WhatsApp after several clicking the \"block\" button.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sale@chat-api.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.InlineResponse2003 = void 0;
var InlineResponse2003 = /** @class */ (function () {
    function InlineResponse2003() {
    }
    InlineResponse2003.getAttributeTypeMap = function () {
        return InlineResponse2003.attributeTypeMap;
    };
    InlineResponse2003.discriminator = undefined;
    InlineResponse2003.attributeTypeMap = [
        {
            "name": "accountStatus",
            "baseName": "accountStatus",
            "type": "InlineResponse2003.AccountStatusEnum"
        }
    ];
    return InlineResponse2003;
}());
exports.InlineResponse2003 = InlineResponse2003;
(function (InlineResponse2003) {
    var AccountStatusEnum;
    (function (AccountStatusEnum) {
        AccountStatusEnum[AccountStatusEnum["SentToWhatsApp"] = 'Retry request sent to WhatsApp'] = "SentToWhatsApp";
        AccountStatusEnum[AccountStatusEnum["NotSentBecauseReasonDontEqualsSyncing"] = 'Retry request not sent because reason don\'t equals \"syncing\"'] = "NotSentBecauseReasonDontEqualsSyncing";
    })(AccountStatusEnum = InlineResponse2003.AccountStatusEnum || (InlineResponse2003.AccountStatusEnum = {}));
})(InlineResponse2003 = exports.InlineResponse2003 || (exports.InlineResponse2003 = {}));
exports.InlineResponse2003 = InlineResponse2003;
