"use strict";
/**
 * Chat API SDK
 * The SDK allows you to receive and send messages through your WhatsApp account. [Sign up now](https://app.chat-api.com/)  The Chat API is based on the WhatsApp WEB protocol and excludes the ban both when using libraries from mgp25 and the like. Despite this, your account can be banned by anti-spam system WhatsApp after several clicking the \"block\" button.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sale@chat-api.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.InlineResponse2002 = void 0;
var InlineResponse2002 = /** @class */ (function () {
    function InlineResponse2002() {
    }
    InlineResponse2002.getAttributeTypeMap = function () {
        return InlineResponse2002.attributeTypeMap;
    };
    InlineResponse2002.discriminator = undefined;
    InlineResponse2002.attributeTypeMap = [
        {
            "name": "accountStatus",
            "baseName": "accountStatus",
            "type": "InlineResponse2002.AccountStatusEnum"
        }
    ];
    return InlineResponse2002;
}());
exports.InlineResponse2002 = InlineResponse2002;
(function (InlineResponse2002) {
    var AccountStatusEnum;
    (function (AccountStatusEnum) {
        AccountStatusEnum[AccountStatusEnum["SentToWhatsApp"] = 'Expiry request sent to WhatsApp'] = "SentToWhatsApp";
        AccountStatusEnum[AccountStatusEnum["NotSentBecauseSubstatusDontEqualsExpired"] = 'Expiry request not sent because substatus don\'t equals \"expired\"'] = "NotSentBecauseSubstatusDontEqualsExpired";
    })(AccountStatusEnum = InlineResponse2002.AccountStatusEnum || (InlineResponse2002.AccountStatusEnum = {}));
})(InlineResponse2002 = exports.InlineResponse2002 || (exports.InlineResponse2002 = {}));
exports.InlineResponse2002 = InlineResponse2002;
