"use strict";
/**
 * Chat API SDK
 * The SDK allows you to receive and send messages through your WhatsApp account. [Sign up now](https://app.chat-api.com/)  The Chat API is based on the WhatsApp WEB protocol and excludes the ban both when using libraries from mgp25 and the like. Despite this, your account can be banned by anti-spam system WhatsApp after several clicking the \"block\" button.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sale@chat-api.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.OutboundAction = void 0;
var OutboundAction = /** @class */ (function () {
    function OutboundAction() {
    }
    OutboundAction.getAttributeTypeMap = function () {
        return OutboundAction.attributeTypeMap;
    };
    OutboundAction.discriminator = undefined;
    OutboundAction.attributeTypeMap = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "OutboundAction.TypeEnum"
        },
        {
            "name": "lastTry",
            "baseName": "last_try",
            "type": "number"
        },
        {
            "name": "jsonData",
            "baseName": "json_data",
            "type": "object"
        }
    ];
    return OutboundAction;
}());
exports.OutboundAction = OutboundAction;
(function (OutboundAction) {
    var TypeEnum;
    (function (TypeEnum) {
        TypeEnum[TypeEnum["CreateGroup"] = 'create group'] = "CreateGroup";
        TypeEnum[TypeEnum["AddGroupParticipant"] = 'add group participant'] = "AddGroupParticipant";
        TypeEnum[TypeEnum["RemoveGroupParticipant"] = 'remove group participant'] = "RemoveGroupParticipant";
        TypeEnum[TypeEnum["PromoteGroupParticipant"] = 'promote group participant'] = "PromoteGroupParticipant";
        TypeEnum[TypeEnum["DemoteGroupParticipant"] = 'demote group participant'] = "DemoteGroupParticipant";
        TypeEnum[TypeEnum["ReadChat"] = 'read chat'] = "ReadChat";
    })(TypeEnum = OutboundAction.TypeEnum || (OutboundAction.TypeEnum = {}));
})(OutboundAction = exports.OutboundAction || (exports.OutboundAction = {}));
exports.OutboundAction = OutboundAction;
